### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by thisandagain** [mozilla/api.webmaker.org#16]
What instrumentation do we want / need for the API?

- Response time (ms)
- Error rates
- Uptime (external by locale)
- Response time (external by locale)
- ???

/cc @jbuck @simonwex @davidascher

**Comment by thisandagain** [comment]
I recommend [nodetime](https://nodetime.com/) as an alternative to NewRelic, though we still need a vendor / solution for 3rd party monitoring and log aggregation / storage.

**Comment by davidascher** [comment]
We also want to count calls.

**Comment by cadecairos** [comment]
@thisandagain I looked into nodetime - their nodejs agent doesn't appear to work on 0.12.x ... I get compilation errors from their native bindings when I try to install it.

**Comment by cadecairos** [comment]
I checked this out a bit further, looks like their native extensions fail to compile (at least for me) when using node 0.12.2 - and they don't have a pre-compiled fallback for node 0.12.2

**Comment by cadecairos** [comment]
> Hi Chris,
>
> We have no plans to support 0.12 in nodetime. Our sister product, AppDynamics for Node.js, will offer this support in the near future.
> 
> Regards,
>
> Nodetime Support 

D:

**Comment by thisandagain** [comment]
Ah! They got bought ... thanks for the follow-up @cadecairos

**Comment by cadecairos** [comment]
I can't find any hosted metrics services that support node.js >= 0.12 other than newrelic.

AppDynamics claims support is coming, but that doesn't help us...

**Comment by cadecairos** [comment]
Reference: https://docs.appdynamics.com/display/PRO40/Node.js+Supported+Environments

**Comment by cadecairos** [comment]
What shall we do here? Does anyone know of metrics services that work with Hapi and node 0.12.x

**Comment by thisandagain** [comment]
@simonwex Can you please work with @cadecairos to get this wrapped up by EOW?

**Comment by cadecairos** [comment]
pulling in @jbuck here too - What do you suggest we do here?

**Comment by cadecairos** [comment]
@jbuck @simonwex Should we just settle for newrelic? Does anyone know of other node 0.12.x compatible instrumentation services?

**Comment by cadecairos** [comment]
I found this. Not sure about it's performance/pricing and how it compares.

http://www.appneta.com/products/traceview/

**Comment by cadecairos** [comment]
datadog looks way less expensive (https://www.datadoghq.com/pricing/), but we'll have to do a lot of manual instrumentation work: https://www.npmjs.com/package/datadog-metrics

**Comment by simonwex** [comment]
@cadecairos I think it makes sense to use newrelic here. We've got to try to minimize our use of it because of the cost and eventually find a permanent replacement. I'd say now's not the time, though.
